/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import core.MainGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author 00220682
 */
public class LinkGenerator extends JFrameHTMLGen implements ActionListener {
    private final String boilerplate = "";
//"<html>\n" +
////"    <head>\n" +
////"        <title>Example Jump List</title>\n" +
////"    </head>\n" +
////"    <body>\n" +
////"        <select>\n" +
////"            \n" +
////"        </select>\n" +
////"    </body>\n" +
//"</html>";

    /**
     * Creates new form JumpListGenerator
     */
    public LinkGenerator() {
        initComponents();
        txtDoc.setText(boilerplate);
        btnReset.addActionListener(this);
        btnAdd.addActionListener(this);
        btnSave.addActionListener(this);
        btnFin.addActionListener(this);
    }

    //Sets up the references references
    public LinkGenerator(MainGUI parent) {
        this();
        this.parent = parent;
        super.txtDoc = this.txtDoc;
        super.boilerplate = this.boilerplate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Link Generator");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Display Text");
        jPanel1.add(jLabel1);
        jPanel1.add(txtDisplay);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("URL");
        jPanel1.add(jLabel2);
        jPanel1.add(txtURL);
        jPanel1.add(jLabel3);

        btnAdd.setText("Create Link");
        jPanel1.add(btnAdd);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnFin.setText("Add Link");
        jPanel2.add(btnFin);

        btnReset.setText("Start Over");
        jPanel2.add(btnReset);

        btnSave.setText("Save to File");
        jPanel2.add(btnSave);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        jScrollPane1.setViewportView(txtDoc);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(592, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextArea txtDoc;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object source = ae.getSource();
        if (source == btnReset) {
            startOver();
        } else if (source == btnAdd) {
            addOption();
        } else if (source == btnSave) {
            save();
        } else if (source == btnFin) {
            add();
        }
    }

    public void addOption() {
        if (txtDisplay.getText().length() == 0) {
            return;
        }
        try {
            StringBuilder sb = new StringBuilder(64);
            sb.append("<a href=\"");
            sb.append(txtURL.getText());
            sb.append("\">");
            sb.append(txtDisplay.getText());
            sb.append("</a>\n\n");
            txtDoc.insert(sb.toString(), 0);
            txtURL.setText("");
            txtDisplay.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to add option - missing </select>");
        }
    }

}
