/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import core.MainGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author 00220682
 */
public class TableGenerator extends JFrameHTMLGen implements ActionListener {

    private final String boilerplate = "<table>\n"
            + "\t<tr>\n"
            + "\t\t<th>First name</th>\n"
            + "\t\t<th>Last name</th>\n"
            + "\t\t<th>Age</th>\n"
            + "\t</tr>\n"
            + "\t<tr>\n"
            + "\t\t<td>Jill</td>\n"
            + "\t\t<td>Smith</td>\n"
            + "\t\t<td>50</td>\n"
            + "\t</tr>\n"
            + "\t<tr>\n"
            + "\t\t<td>Eve</td>\n"
            + "\t\t<td>Jackson</td>\n"
            + "\t\t<td>94</td>\n"
            + "\t</tr>\n"
            + "</table>";

    /**
     * Creates new form JumpListGenerator
     */
    public TableGenerator() {
        initComponents();
        txtDoc.setText(boilerplate);
        btnReset.addActionListener(this);
        btnCreate.addActionListener(this);
        btnSave.addActionListener(this);
        btnFin.addActionListener(this);
    }

    //Sets up the references references
    public TableGenerator(MainGUI parent) {
        this();
        this.parent = parent;
        super.txtDoc = this.txtDoc;
        super.boilerplate = this.boilerplate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rowText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        colText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Table Generator");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        jPanel1.setLayout(new java.awt.GridLayout(3, 4, 5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number of Rows");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jPanel1.add(rowText);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Number of Columns");
        jPanel1.add(jLabel2);
        jPanel1.add(colText);
        jPanel1.add(jLabel3);

        btnCreate.setText("Create Table");
        jPanel1.add(btnCreate);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnFin.setText("Add Table");
        jPanel2.add(btnFin);

        btnReset.setText("Start Over");
        jPanel2.add(btnReset);

        btnSave.setText("Save to File");
        jPanel2.add(btnSave);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        txtDoc.setTabSize(4);
        jScrollPane1.setViewportView(txtDoc);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(592, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField colText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rowText;
    private javax.swing.JTextArea txtDoc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object source = ae.getSource();
        if (source == btnReset) {
            startOver();
        } else if (source == btnCreate) {
            createTable();
        } else if (source == btnSave) {
            save();
        } else if (source == btnFin) {
            add();
        }
    }

    public void createTable() {
        if (rowText.getText().length() == 0) {
            return;
        }
        if (colText.getText().length() == 0) {
            return;
        }
        try {
            txtDoc.setText("");
            StringBuilder sb = new StringBuilder(64);
            //At the front of every table
            sb.append("<table>\n");
            //Nested for loop, starting with every row
            int row = Integer.parseInt(rowText.getText());
            int col = Integer.parseInt(colText.getText());
            for (int r = 1; r <= row; r++) {
                System.out.println(r);
                System.out.println(row);
                //Inside loop for every column in this particular row
                sb.append("\t<tr>\n");
                for (int c = 1; c <= col; c++) {
                    String option = JOptionPane.showInputDialog("Please enter the " + numberFormatter(c)
                            + " element of the " + numberFormatter(r) + " row.");
                    sb.append("\t\t<td>");
                    sb.append("" + option);
                    sb.append("</td>\n");
                }
                sb.append("\t</tr>\n");
            }
            //At the end of every table
            sb.append("</table>\n");
            txtDoc.insert(sb.toString(), 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error has occurred");
        }
    }

    // Properly formats numbers in the style of
    // 1st 2nd 3rd 4th ect
    public String numberFormatter(int i) {
        String append;
        switch (i) {
            case 1:
                append = "st";
                break;
            case 2:
                append = "nd";
                break;
            case 3:
                append = "rd";
                break;
            default:
                append = "th";
                break;
        }
        String result = i + append;
        return result;
    }

}
