/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core;

import components.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author 01048750
 */
public class MainGUI extends JFrameHTMLGen implements ActionListener, DocumentListener {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        ImageButton.addActionListener(this);
        JumpListButton.addActionListener(this);
        LinkButton.addActionListener(this);
        TableButton.addActionListener(this);
        SaveButton.addActionListener(this);
        super.txtDoc = this.txtDoc;
        super.boilerplate = importHTML("src\\Examples\\template.html");
        super.startOver();
        displayHTML();
        // Adds a document listener so that the HTML preview updates on changes
        Document doc = txtDoc.getDocument();
        doc.addDocumentListener(this);
    }
    
    

    //Imports the base file template from a html file with name name.
    private String importHTML(String name) {
        System.out.println("Running importHTML");
        StringBuilder contentBuilder = new StringBuilder();
        try {
            BufferedReader in = new BufferedReader(new FileReader(name));
            String str;
            while ((str = in.readLine()) != null) {
                contentBuilder.append(str + "\n");
            }
            in.close();
        } catch (IOException e) {
            System.out.println("Error in importHTML");
            System.out.println(e.getMessage());
        }
        return contentBuilder.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        SaveButton = new javax.swing.JButton();
        LinkButton = new javax.swing.JButton();
        ImageButton = new javax.swing.JButton();
        TableButton = new javax.swing.JButton();
        JumpListButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML Generator");

        jToolBar1.setRollover(true);

        SaveButton.setText("Save");
        SaveButton.setFocusable(false);
        SaveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(SaveButton);

        LinkButton.setText("Insert Link");
        LinkButton.setFocusable(false);
        LinkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LinkButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(LinkButton);

        ImageButton.setText("Insert Image");
        ImageButton.setFocusable(false);
        ImageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ImageButton);

        TableButton.setText("Insert Table");
        TableButton.setFocusable(false);
        TableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TableButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(TableButton);

        JumpListButton.setText("Insert Jump List");
        JumpListButton.setFocusable(false);
        JumpListButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JumpListButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JumpListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumpListButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(JumpListButton);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setResizeWeight(0.5);

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        txtDoc.setTabSize(4);
        txtDoc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDoc);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(166, 96));

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setPreferredSize(new java.awt.Dimension(166, 96));
        jScrollPane2.setViewportView(jEditorPane1);

        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1087, 841));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JumpListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumpListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumpListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImageButton;
    private javax.swing.JButton JumpListButton;
    private javax.swing.JButton LinkButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton TableButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtDoc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object source = ae.getSource();
        if (source == ImageButton) {
            new ImageGenerator(this).setVisible(true);
        } else if (source == JumpListButton) {
            new JumpListGenerator(this).setVisible(true);
        } else if (source == LinkButton) {
            new LinkGenerator(this).setVisible(true);
        } else if (source == SaveButton) {
            save();
        } else if (source == TableButton) {
            new TableGenerator(this).setVisible(true);
        }
        displayHTML();
    }

    // Inserts text at the current curser position
    public void addText(String text) {
        txtDoc.insert(text, txtDoc.getCaretPosition());
    }

    public void displayHTML() {
        jEditorPane1.setText(txtDoc.getText());
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        displayHTML();
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        displayHTML();
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        displayHTML();
    }
}
